server:
  port: 8081
spring:
  config:
    import: optional:eureka-server:http://localhost:8761
  application:
    name: product-service
management:
  endpoints:
    web:
      exposure:
        include: ['*']
